"""listing history and provider sources

Revision ID: 4fbe7604a7a8
Revises: 0001_scrape_runs
Create Date: 2026-09-29 18:11:50.814981
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4fbe7604a7a8'
down_revision: Union[str, None] = '0001_scrape_runs'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=48), nullable=False),
    sa.Column('external_id', sa.String(length=160), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_detail_fetch_at', sa.DateTime(), nullable=True),
    sa.Column('removed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=24), server_default='active', nullable=False),
    sa.Column('missing_run_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('current_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'external_id', name='uq_listing_provider_external_id')
    )
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.create_index('ix_listings_status_last_seen', ['status', 'last_seen_at'], unique=False)

    op.create_table('search_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('filters_json', sa.JSON(), nullable=False),
    sa.Column('preferences_json', sa.JSON(), nullable=False),
    sa.Column('initial_import_mode', sa.String(length=24), server_default='analyze_all', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('listing_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('observed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price_amount', sa.Integer(), nullable=True),
    sa.Column('price_currency', sa.String(length=3), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('make', sa.String(length=120), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('generation', sa.String(length=120), nullable=True),
    sa.Column('trim', sa.String(length=160), nullable=True),
    sa.Column('mileage_km', sa.Integer(), nullable=True),
    sa.Column('fuel', sa.String(length=32), nullable=True),
    sa.Column('engine_cc', sa.Integer(), nullable=True),
    sa.Column('power_kw', sa.Integer(), nullable=True),
    sa.Column('transmission', sa.String(length=32), nullable=True),
    sa.Column('drive', sa.String(length=24), nullable=True),
    sa.Column('body_type', sa.String(length=48), nullable=True),
    sa.Column('doors', sa.Integer(), nullable=True),
    sa.Column('seats', sa.Integer(), nullable=True),
    sa.Column('location_raw', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.Column('seller_type', sa.String(length=32), nullable=True),
    sa.Column('structured_json', sa.JSON(), nullable=False),
    sa.Column('features_json', sa.JSON(), nullable=False),
    sa.Column('condition_json', sa.JSON(), nullable=False),
    sa.Column('provider_payload_json', sa.JSON(), nullable=False),
    sa.Column('images_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('listing_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_snapshots_listing_observed', ['listing_id', 'observed_at'], unique=False)

    op.create_table('listing_user_state',
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=32), server_default='new', nullable=False),
    sa.Column('notes', sa.Text(), server_default='', nullable=False),
    sa.Column('rejection_reason', sa.String(length=32), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('listing_id')
    )
    op.create_table('profile_listing_matches',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('first_matched_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_matched_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('hard_filter_pass', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('profile_fit_score', sa.Integer(), nullable=True),
    sa.Column('match_details_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['search_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id', 'listing_id')
    )
    with op.batch_alter_table('profile_listing_matches', schema=None) as batch_op:
        batch_op.create_index('ix_profile_matches_last_matched', ['last_matched_at'], unique=False)

    op.create_table('provider_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=48), nullable=False),
    sa.Column('search_url', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('source_settings_json', sa.JSON(), nullable=False),
    sa.Column('first_scan_completed', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['search_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'provider', 'search_url', name='uq_source_profile_provider_url')
    )
    op.create_table('provider_source_listings',
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('missing_run_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['provider_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('source_id', 'listing_id')
    )
    with op.batch_alter_table('provider_source_listings', schema=None) as batch_op:
        batch_op.create_index('ix_source_listings_listing_active', ['listing_id', 'active'], unique=False)
    op.create_table('scrape_run_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('context_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['scrape_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scrape_run_messages', schema=None) as batch_op:
        batch_op.create_index('ix_run_messages_run_created', ['run_id', 'created_at'], unique=False)

    op.create_table('listing_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('old_value_json', sa.JSON(), nullable=True),
    sa.Column('new_value_json', sa.JSON(), nullable=True),
    sa.Column('snapshot_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['listing_snapshots.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('listing_events', schema=None) as batch_op:
        batch_op.create_index('ix_listing_events_listing_occurred', ['listing_id', 'occurred_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing_events', schema=None) as batch_op:
        batch_op.drop_index('ix_listing_events_listing_occurred')

    op.drop_table('listing_events')
    with op.batch_alter_table('scrape_run_messages', schema=None) as batch_op:
        batch_op.drop_index('ix_run_messages_run_created')

    op.drop_table('scrape_run_messages')
    with op.batch_alter_table('provider_source_listings', schema=None) as batch_op:
        batch_op.drop_index('ix_source_listings_listing_active')

    op.drop_table('provider_source_listings')
    op.drop_table('provider_sources')
    with op.batch_alter_table('profile_listing_matches', schema=None) as batch_op:
        batch_op.drop_index('ix_profile_matches_last_matched')

    op.drop_table('profile_listing_matches')
    op.drop_table('listing_user_state')
    with op.batch_alter_table('listing_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_snapshots_listing_observed')

    op.drop_table('listing_snapshots')
    op.drop_table('search_profiles')
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_index('ix_listings_status_last_seen')

    op.drop_table('listings')
    # ### end Alembic commands ###
